# Jekyll
pygments: true
markdown: redcarpet
paginate: 10 
permalink: /:year/:title/ 
exclude: ["README.md"]
auto: true
pygments: true
baseurl: /
url: http://johnmdonahue.com
title: johnmdonahue
author:
  name: John Donahue
  email: johnmdonahue@gmail.com
  github: johnmdonahue
  twitter: johnmdonahue
  gravatar: d3e55f4860218d6a2fcb33726c29005f
links: []
