# Jekyll
markdown: redcarpet2
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
pygments: true
permalink: /:year/:title/ 
exclude: ["README.md", "less", "CNAME"]
auto: true
baseurl: /
url: http://johnmdonahue.com
title: johnmdonahue
author:
  name: John Donahue
  email: johnmdonahue@gmail.com
  github: johnmdonahue
  twitter: johnmdonahue
  gravatar: d3e55f4860218d6a2fcb33726c29005f
